#!/usr/bin/env python

from __future__ import print_function
from phaser import Phase, Phaser

""" Hello World implementation with phaser. """

class PrintPhase(Phase):

    def execute(self, character):
        print(character, end='')

    def iter(self):
        return iter(self.characters)

class Hello(PrintPhase):
    """ Print 'Hello ' """

    def __init__(self):
        self.characters = "Hello "

class World(PrintPhase):
    """ Print 'World!' """

    def __init__(self):
        self.characters = "World!"

    def postexec(self):
        print("")

if __name__ == '__main__':
    Phaser(phases=[Hello(), World()])()
