#!/usr/bin/env python

""" Hello World implementation with phaser. """

from __future__ import print_function
import os
from phaser import Phase, Phaser

class PrintPhase(Phase):

    def execute(self, character):
        print(character, end='')

    def iter(self):
        return iter(self.characters)

class File(Phase):

    def __init__(self, n):
        self.string = "Hello World!"
        self.file_name = "hello.txt"
        self.repeats = n
        self.__doc__ = "Write 'Hello World!' to a file %i times " % n
        self.description = "File%i" % n

    def precondition(self):
        if os.path.exists(self.file_name):
            raise Exception("File '%s' exists!" % self.file_name)

    def preexec(self):
        self.fp = open(self.file_name, 'w')

    def execute(self, _):
        self.fp.write(self.string)

    def postexec(self):
        self.fp.flush()
        self.fp.close()

    def iter(self):
        return iter(range(23))

class Hello(PrintPhase):
    """ Print 'Hello ' """

    def __init__(self):
        self.characters = "Hello "

class World(PrintPhase):
    """ Print 'World!' """

    def __init__(self):
        self.characters = "World!"

    def postexec(self):
        print("")

if __name__ == '__main__':
    phsr = Phaser(phases=[Hello(), World(), File(23)])
    phsr()
