#!/usr/bin/env python

""" Hello World implementation with PyPhaser. """

from __future__ import print_function
import os
from phaser import Phase, IterPhase, Phaser


class Hello(Phase):
    """ Print 'Hello ' """

    def execute(self):
        print('Hello ', end='')

class World(IterPhase):
    """ Print 'World!' """

    def __init__(self):
        self.characters = 'World!'

    def function(self, character):
        print(character, end='')

    def iter(self):
        return iter(self.characters)

    def postexec(self):
        print("")

if __name__ == '__main__':
    phsr = Phaser(phases=[Hello(), World()])
    phsr()
